/**:
  ros__parameters:
    wheel_radius: 0.17 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.12 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.015 # between front wheel center and rear wheel center
    wheel_tread: 0.57 # between left wheel center and right wheel center
    front_overhang: 0.235 # between front wheel center and vehicle front
    rear_overhang: 0.26 # between rear wheel center and vehicle rear
    left_overhang: 0.0725 # between left wheel center and vehicle left
    right_overhang: 0.0725 # between right wheel center and vehicle right
    vehicle_height: 1.328
    max_steer_angle: 0.7505 # [rad]