sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.646504
    y: -0.0353747
    z: -0.836021
    roll: 0.16
    pitch: 0.34
    yaw: 3.49