sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  camera/camera0/camera_link:
    x: 0.2
    y: 0.0
    z: -0.3
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  camera/camera1/camera_link:
    x: -1.0
    y: 0.0
    z: -0.3
    roll: 0.0
    pitch: 0.0
    yaw: 3.14  # 背對

  camera/camera3/camera_link:
    x: 0.0
    y: 0.6
    z: -0.3
    roll: 0.0
    pitch: 0.0
    yaw: 1.57  # 向左

  camera/camera2/camera_link:
    x: 0.0
    y: -0.6
    z: -0.3
    roll: 0.0
    pitch: 0.0
    yaw: -1.57  # 向右
